"""Replace payment tracking fields with single pagado boolean

Revision ID: 559bd173ffb0
Revises: f91ffa888bca
Create Date: 2026-01-17 03:43:36.265897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '559bd173ffb0'
down_revision = 'f91ffa888bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado', sa.Boolean(), nullable=True))
        batch_op.drop_column('fecha_ultimo_pago')
        batch_op.drop_column('mes_pagado')
        batch_op.drop_column('pagado_este_mes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado_este_mes', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mes_pagado', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_ultimo_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('pagado')

    # ### end Alembic commands ###
