"""Agregar tabla de parametros del sistema

Revision ID: 92b38c89cf67
Revises: 9c36dff2886c
Create Date: 2025-12-26 14:12:45.564252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b38c89cf67'
down_revision = '9c36dff2886c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('editable', sa.Boolean(), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parametro')
    # ### end Alembic commands ###
