"""Migracion inicial para postgres

Revision ID: 9c36dff2886c
Revises: 
Create Date: 2025-12-24 16:51:03.218324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c36dff2886c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_fiscal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('valor_sbu', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_table('cuenta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=True),
    sa.Column('saldo_inicial', sa.Float(), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('alicuota', sa.Float(), nullable=False),
    sa.Column('esta_arrendado', sa.Boolean(), nullable=True),
    sa.Column('responsable_pago', sa.String(length=20), nullable=True),
    sa.Column('valor_expensa', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ruc_cedula', sa.String(length=20), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('comprobante_url', sa.String(length=200), nullable=True),
    sa.Column('es_transferencia', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cuenta_id'], ['cuenta.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona_contacto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('recibe_notificaciones', sa.Boolean(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantenimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('costo_referencial', sa.Float(), nullable=True),
    sa.Column('foto_antes', sa.String(length=200), nullable=True),
    sa.Column('foto_despues', sa.String(length=200), nullable=True),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipo.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mantenimiento')
    op.drop_table('persona_contacto')
    op.drop_table('movimiento')
    op.drop_table('rubro')
    op.drop_table('proveedor')
    op.drop_table('equipo')
    op.drop_table('departamento')
    op.drop_table('cuenta')
    op.drop_table('configuracion_fiscal')
    # ### end Alembic commands ###
