"""Actualizar modelo de Gastos Recurrentes

Revision ID: a523a6ccd312
Revises: cc4d621a4da1
Create Date: 2026-01-05 17:44:26.641609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a523a6ccd312'
down_revision = 'cc4d621a4da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('gasto_recurrente_movimiento_id_fkey'), type_='foreignkey')
        batch_op.drop_column('anio_especifico')
        batch_op.drop_column('periodicidad')
        batch_op.drop_column('pagado')
        batch_op.drop_column('movimiento_id')
        batch_op.drop_column('fecha_ultimo_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ultimo_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('movimiento_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pagado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('periodicidad', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('anio_especifico', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('gasto_recurrente_movimiento_id_fkey'), 'movimiento', ['movimiento_id'], ['id'])
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
