"""Agregar campos bancarios a Proveedor

Revision ID: c34b6f5064be
Revises: 92b38c89cf67
Create Date: 2025-12-27 17:41:13.026920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c34b6f5064be'
down_revision = '92b38c89cf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('banco', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tipo_cuenta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('numero_cuenta', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('numero_cuenta')
        batch_op.drop_column('tipo_cuenta')
        batch_op.drop_column('banco')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
