"""Agregar modelo de Gastos Recurrentes

Revision ID: cc4d621a4da1
Revises: c34b6f5064be
Create Date: 2026-01-05 16:41:43.444203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4d621a4da1'
down_revision = 'c34b6f5064be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasto_recurrente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('tipo_periodicidad', sa.String(length=20), nullable=False),
    sa.Column('periodicidad', sa.String(length=20), nullable=True),
    sa.Column('meses_base', sa.String(length=50), nullable=False),
    sa.Column('anio_especifico', sa.Integer(), nullable=True),
    sa.Column('pagado', sa.Boolean(), nullable=True),
    sa.Column('fecha_ultimo_pago', sa.DateTime(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gasto_recurrente')
    # ### end Alembic commands ###
