"""Add payment tracking to GastoRecurrente

Revision ID: f91ffa888bca
Revises: a523a6ccd312
Create Date: 2026-01-17 03:15:06.371517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f91ffa888bca'
down_revision = 'a523a6ccd312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagado_este_mes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mes_pagado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_ultimo_pago', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasto_recurrente', schema=None) as batch_op:
        batch_op.drop_column('fecha_ultimo_pago')
        batch_op.drop_column('mes_pagado')
        batch_op.drop_column('pagado_este_mes')

    # ### end Alembic commands ###
